/**
 * Created by sudarshan on 17/1/18.
 */

export const MERCHANT_ACTIONS = {
    GET_LIST : 'GET_LIST',
    DELETE_MERCHANT : 'DELETE_MERCHANT',
    EDIT_MERCHANT : 'EDIT_MERCHANT',
    UPDATE_MERCHANT : 'UPDATE_MERCHANT',
    ADD_MERCHANT : 'ADD_MERCHANT',
    GET_BIDS : 'GET_BIDS'
}